-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 11:59:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`SecteurEntreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SecteurEntreprise` (
  `idSecteurEntreprise` INT NOT NULL,
  `Nom` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSecteurEntreprise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entreprises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entreprises` (
  `idEntreprise` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Pays` VARCHAR(45) NOT NULL,
  `Ville` VARCHAR(45) NOT NULL,
  `CodePostal` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `SecteurEntreprise_idSecteurEntreprise` INT NOT NULL,
  PRIMARY KEY (`idEntreprise`),
  INDEX `fk_Entreprises_SecteurEntreprise1_idx` (`SecteurEntreprise_idSecteurEntreprise` ASC) VISIBLE,
  CONSTRAINT `fk_Entreprises_SecteurEntreprise1`
    FOREIGN KEY (`SecteurEntreprise_idSecteurEntreprise`)
    REFERENCES `mydb`.`SecteurEntreprise` (`idSecteurEntreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilisateurs` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `idEntreprise` INT NULL,
  `Nom` VARCHAR(255) NOT NULL,
  `Prenom` VARCHAR(255) NOT NULL,
  `DateDeNaissance` DATE NOT NULL,
  `Genre` TINYINT NULL,
  `AdressEmail` VARCHAR(255) NOT NULL,
  `MotDePasse` VARCHAR(255) NOT NULL,
  `Adresse` VARCHAR(255) NULL,
  `CodePostal` VARCHAR(255) NULL,
  `Ville` VARCHAR(255) NULL,
  `Pays` VARCHAR(255) NULL,
  PRIMARY KEY (`idUtilisateur`),
  INDEX `fk_Utilisateurs_Entreprises1_idx` (`idEntreprise` ASC) VISIBLE,
  CONSTRAINT `fk_Utilisateurs_Entreprises1`
    FOREIGN KEY (`idEntreprise`)
    REFERENCES `mydb`.`Entreprises` (`idEntreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `idCategorie` INT NOT NULL,
  `Nom` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Artistes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artistes` (
  `idArtistes` INT NOT NULL,
  `Nom` VARCHAR(255) NULL,
  `Prenom` VARCHAR(45) NULL,
  `DateNaissance` VARCHAR(45) NULL,
  `NomArtiste` VARCHAR(45) NOT NULL,
  `Categorie_idCategorie` INT NOT NULL,
  PRIMARY KEY (`idArtistes`),
  INDEX `fk_Artistes_Categorie1_idx` (`Categorie_idCategorie` ASC) VISIBLE,
  CONSTRAINT `fk_Artistes_Categorie1`
    FOREIGN KEY (`Categorie_idCategorie`)
    REFERENCES `mydb`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evenements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evenements` (
  `idEvenement` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `idUtilisateur` INT NOT NULL,
  `Description` TEXT NOT NULL,
  `NbPlaces` INT UNSIGNED NOT NULL,
  `Artistes_idArtistes` INT NOT NULL,
  PRIMARY KEY (`idEvenement`),
  INDEX `fk_Evenements_Utilisateurs1_idx` (`idUtilisateur` ASC) VISIBLE,
  INDEX `fk_Evenements_Artistes1_idx` (`Artistes_idArtistes` ASC) VISIBLE,
  CONSTRAINT `fk_Evenements_Utilisateurs1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evenements_Artistes1`
    FOREIGN KEY (`Artistes_idArtistes`)
    REFERENCES `mydb`.`Artistes` (`idArtistes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lieux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lieux` (
  `Nom` VARCHAR(255) NOT NULL,
  `idLieu` INT NOT NULL AUTO_INCREMENT,
  `idUtilisateur` INT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `CodePostal` VARCHAR(45) NOT NULL,
  `Ville` VARCHAR(45) NOT NULL,
  `Pays` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLieu`),
  INDEX `fk_Lieux_Utilisateurs1_idx` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Lieux_Utilisateurs1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Dates` (
  `idDate` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `idEvenement` INT NOT NULL,
  `idLieu` INT NOT NULL,
  `Prix` DECIMAL(14,2) NOT NULL,
  PRIMARY KEY (`idDate`),
  INDEX `fk_Dates_Evenements_idx` (`idEvenement` ASC) VISIBLE,
  INDEX `fk_Dates_Lieux1_idx` (`idLieu` ASC) VISIBLE,
  CONSTRAINT `fk_Dates_Evenements`
    FOREIGN KEY (`idEvenement`)
    REFERENCES `mydb`.`Evenements` (`idEvenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dates_Lieux1`
    FOREIGN KEY (`idLieu`)
    REFERENCES `mydb`.`Lieux` (`idLieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tickets` (
  `idTicket` INT NOT NULL,
  `idDate` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  `Prix` DECIMAL(14,2) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `DateNaissance` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTicket`),
  INDEX `fk_Tickets_Dates1_idx` (`idDate` ASC) VISIBLE,
  INDEX `fk_Tickets_Utilisateurs1_idx` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Tickets_Dates1`
    FOREIGN KEY (`idDate`)
    REFERENCES `mydb`.`Dates` (`idDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Utilisateurs1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `mydb`.`Utilisateurs` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;