-- MySQL Script generated by MySQL Workbench
-- Mon Dec 14 09:08:08 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Thetickets
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Thetickets
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Thetickets` DEFAULT CHARACTER SET utf8 ;
USE `Thetickets` ;

-- -----------------------------------------------------
-- Table `Thetickets`.`mail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`mail` (
  `idmail` INT NOT NULL AUTO_INCREMENT,
  `mail_adress` VARCHAR(255) NOT NULL,
  `mailcol` VARCHAR(45) NULL,
  `Date_idDate` INT NOT NULL,
  `Date_Lieu_idLieu` INT NOT NULL,
  `Lieu_idLieu` INT NOT NULL,
  PRIMARY KEY (`idmail`),
  INDEX `fk_mail_Date1_idx` (`Date_idDate` ASC, `Date_Lieu_idLieu` ASC) VISIBLE,
  INDEX `fk_mail_Lieu1_idx` (`Lieu_idLieu` ASC) VISIBLE,
  CONSTRAINT `fk_mail_Date1`
    FOREIGN KEY (`Date_idDate` , `Date_Lieu_idLieu`)
    REFERENCES `Thetickets`.`Date` (`idDate` , `Lieu_idLieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mail_Lieu1`
    FOREIGN KEY (`Lieu_idLieu`)
    REFERENCES `Thetickets`.`Lieu` (`idLieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thetickets`.`paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`paiement` (
  `idpaiement` INT NOT NULL AUTO_INCREMENT,
  `prix` INT NOT NULL,
  `qrcode_idqrcode` INT NOT NULL,
  PRIMARY KEY (`idpaiement`),
  INDEX `fk_paiement_qrcode1_idx` (`qrcode_idqrcode` ASC) VISIBLE,
  CONSTRAINT `fk_paiement_qrcode1`
    FOREIGN KEY (`qrcode_idqrcode`)
    REFERENCES `Thetickets`.`qrcode` (`idqrcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thetickets`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NULL,
  `Tickets_idTickets` INT NOT NULL,
  `paiement_idpaiement` INT NOT NULL,
  `qrcode_idqrcode` INT NOT NULL,
  PRIMARY KEY (`iduser`, `paiement_idpaiement`),
  INDEX `fk_user_Tickets1_idx` (`Tickets_idTickets` ASC) VISIBLE,
  INDEX `fk_user_paiement1_idx` (`paiement_idpaiement` ASC) VISIBLE,
  INDEX `fk_user_qrcode1_idx` (`qrcode_idqrcode` ASC) VISIBLE,
  CONSTRAINT `fk_user_Tickets1`
    FOREIGN KEY (`Tickets_idTickets`)
    REFERENCES `Thetickets`.`Tickets` (`idTickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_paiement1`
    FOREIGN KEY (`paiement_idpaiement`)
    REFERENCES `Thetickets`.`paiement` (`idpaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_qrcode1`
    FOREIGN KEY (`qrcode_idqrcode`)
    REFERENCES `Thetickets`.`qrcode` (`idqrcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thetickets`.`qrcode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`qrcode` (
  `idqrcode` INT NOT NULL AUTO_INCREMENT,
  `QrCode` VARCHAR(255) NOT NULL,
  `Date_idDate` INT NOT NULL,
  `Date_Lieu_idLieu` INT NOT NULL,
  `Lieu_idLieu` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `user_paiement_idpaiement` INT NOT NULL,
  `Events_idEvents` INT NOT NULL,
  `Events_paiement_idpaiement` INT NOT NULL,
  `paiement_idpaiement` INT NOT NULL,
  PRIMARY KEY (`idqrcode`),
  INDEX `fk_qrcode_Date1_idx` (`Date_idDate` ASC, `Date_Lieu_idLieu` ASC) VISIBLE,
  INDEX `fk_qrcode_Lieu1_idx` (`Lieu_idLieu` ASC) VISIBLE,
  INDEX `fk_qrcode_user1_idx` (`user_iduser` ASC, `user_paiement_idpaiement` ASC) VISIBLE,
  INDEX `fk_qrcode_Events1_idx` (`Events_idEvents` ASC, `Events_paiement_idpaiement` ASC) VISIBLE,
  INDEX `fk_qrcode_paiement1_idx` (`paiement_idpaiement` ASC) VISIBLE,
  CONSTRAINT `fk_qrcode_Date1`
    FOREIGN KEY (`Date_idDate` , `Date_Lieu_idLieu`)
    REFERENCES `Thetickets`.`Date` (`idDate` , `Lieu_idLieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qrcode_Lieu1`
    FOREIGN KEY (`Lieu_idLieu`)
    REFERENCES `Thetickets`.`Lieu` (`idLieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qrcode_user1`
    FOREIGN KEY (`user_iduser` , `user_paiement_idpaiement`)
    REFERENCES `Thetickets`.`user` (`iduser` , `paiement_idpaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qrcode_Events1`
    FOREIGN KEY (`Events_idEvents` , `Events_paiement_idpaiement`)
    REFERENCES `Thetickets`.`Events` (`idEvents` , `paiement_idpaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_qrcode_paiement1`
    FOREIGN KEY (`paiement_idpaiement`)
    REFERENCES `Thetickets`.`paiement` (`idpaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thetickets`.`Date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`Date` (
  `idDate` INT NOT NULL AUTO_INCREMENT,
  `eventdate` DATE NOT NULL,
  `Datecol` VARCHAR(45) NULL,
  `Events_idEvents` INT NOT NULL,
  `Events_paiement_idpaiement` INT NOT NULL,
  `Lieu_idLieu` INT NOT NULL,
  `Events_idEvents1` INT NOT NULL,
  `Events_paiement_idpaiement1` INT NOT NULL,
  `mail_idmail` INT NOT NULL,
  `qrcode_idqrcode` INT NOT NULL,
  PRIMARY KEY (`idDate`, `Lieu_idLieu`),
  INDEX `fk_Date_Events1_idx` (`Events_idEvents` ASC, `Events_paiement_idpaiement` ASC) VISIBLE,
  INDEX `fk_Date_Events2_idx` (`Events_idEvents1` ASC, `Events_paiement_idpaiement1` ASC) VISIBLE,
  INDEX `fk_Date_mail1_idx` (`mail_idmail` ASC) VISIBLE,
  INDEX `fk_Date_qrcode1_idx` (`qrcode_idqrcode` ASC) VISIBLE,
  CONSTRAINT `fk_Date_Events1`
    FOREIGN KEY (`Events_idEvents` , `Events_paiement_idpaiement`)
    REFERENCES `Thetickets`.`Events` (`idEvents` , `paiement_idpaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Date_Events2`
    FOREIGN KEY (`Events_idEvents1` , `Events_paiement_idpaiement1`)
    REFERENCES `Thetickets`.`Events` (`idEvents` , `paiement_idpaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Date_mail1`
    FOREIGN KEY (`mail_idmail`)
    REFERENCES `Thetickets`.`mail` (`idmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Date_qrcode1`
    FOREIGN KEY (`qrcode_idqrcode`)
    REFERENCES `Thetickets`.`qrcode` (`idqrcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thetickets`.`Lieu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`Lieu` (
  `idLieu` INT NOT NULL AUTO_INCREMENT,
  `LieuEvent` VARCHAR(255) NOT NULL,
  `CodePostal` INT NOT NULL,
  `NomEtablissement` VARCHAR(255) NOT NULL,
  `Date_idDate` INT NOT NULL,
  `Date_Lieu_idLieu` INT NOT NULL,
  `Date_idDate1` INT NOT NULL,
  `Date_Lieu_idLieu1` INT NOT NULL,
  `mail_idmail` INT NOT NULL,
  `Tickets_idTickets` INT NOT NULL,
  `qrcode_idqrcode` INT NOT NULL,
  PRIMARY KEY (`idLieu`),
  INDEX `fk_Lieu_Date1_idx` (`Date_idDate` ASC, `Date_Lieu_idLieu` ASC) VISIBLE,
  INDEX `fk_Lieu_Date2_idx` (`Date_idDate1` ASC, `Date_Lieu_idLieu1` ASC) VISIBLE,
  INDEX `fk_Lieu_mail1_idx` (`mail_idmail` ASC) VISIBLE,
  INDEX `fk_Lieu_Tickets1_idx` (`Tickets_idTickets` ASC) VISIBLE,
  INDEX `fk_Lieu_qrcode1_idx` (`qrcode_idqrcode` ASC) VISIBLE,
  CONSTRAINT `fk_Lieu_Date1`
    FOREIGN KEY (`Date_idDate` , `Date_Lieu_idLieu`)
    REFERENCES `Thetickets`.`Date` (`idDate` , `Lieu_idLieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lieu_Date2`
    FOREIGN KEY (`Date_idDate1` , `Date_Lieu_idLieu1`)
    REFERENCES `Thetickets`.`Date` (`idDate` , `Lieu_idLieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lieu_mail1`
    FOREIGN KEY (`mail_idmail`)
    REFERENCES `Thetickets`.`mail` (`idmail`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lieu_Tickets1`
    FOREIGN KEY (`Tickets_idTickets`)
    REFERENCES `Thetickets`.`Tickets` (`idTickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lieu_qrcode1`
    FOREIGN KEY (`qrcode_idqrcode`)
    REFERENCES `Thetickets`.`qrcode` (`idqrcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thetickets`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`Tickets` (
  `idTickets` INT NOT NULL AUTO_INCREMENT,
  `ticket number` VARCHAR(255) NOT NULL,
  `Ticketscol` VARCHAR(45) NOT NULL,
  `Lieu_idLieu` INT NOT NULL,
  PRIMARY KEY (`idTickets`),
  INDEX `fk_Tickets_Lieu1_idx` (`Lieu_idLieu` ASC) VISIBLE,
  CONSTRAINT `fk_Tickets_Lieu1`
    FOREIGN KEY (`Lieu_idLieu`)
    REFERENCES `Thetickets`.`Lieu` (`idLieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thetickets`.`Entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`Entreprise` (
  `idEntreprise` INT NOT NULL AUTO_INCREMENT,
  `nameentreprise` VARCHAR(255) NOT NULL,
  `Events_idEvents` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idEntreprise`),
  INDEX `fk_Entreprise_Events1_idx` (`Events_idEvents` ASC) VISIBLE,
  INDEX `fk_Entreprise_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Entreprise_Events1`
    FOREIGN KEY (`Events_idEvents`)
    REFERENCES `Thetickets`.`Events` (`idEvents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entreprise_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `Thetickets`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thetickets`.`Hôte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`Hôte` (
  `idHôte` INT NOT NULL AUTO_INCREMENT,
  `namehote` VARCHAR(255) NOT NULL,
  `Entreprise_idEntreprise` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idHôte`),
  INDEX `fk_Hôte_Entreprise1_idx` (`Entreprise_idEntreprise` ASC) VISIBLE,
  INDEX `fk_Hôte_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Hôte_Entreprise1`
    FOREIGN KEY (`Entreprise_idEntreprise`)
    REFERENCES `Thetickets`.`Entreprise` (`idEntreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hôte_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `Thetickets`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thetickets`.`Photos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`Photos` (
  `idPhotos` INT NOT NULL AUTO_INCREMENT,
  `Photos` VARCHAR(255) NOT NULL,
  `Events_idEvents` INT NOT NULL,
  `Events_paiement_idpaiement` INT NOT NULL,
  PRIMARY KEY (`idPhotos`),
  INDEX `fk_Photos_Events1_idx` (`Events_idEvents` ASC, `Events_paiement_idpaiement` ASC) VISIBLE,
  CONSTRAINT `fk_Photos_Events1`
    FOREIGN KEY (`Events_idEvents` , `Events_paiement_idpaiement`)
    REFERENCES `Thetickets`.`Events` (`idEvents` , `paiement_idpaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thetickets`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`Events` (
  `idEvents` INT NOT NULL AUTO_INCREMENT,
  `Events` VARCHAR(255) NULL,
  `Tickets_idTickets` INT NOT NULL,
  `Hôte_idHôte` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `paiement_idpaiement` INT NOT NULL,
  `Photos_idPhotos` INT NOT NULL,
  `Date_idDate` INT NOT NULL,
  `qrcode_idqrcode` INT NOT NULL,
  PRIMARY KEY (`idEvents`, `paiement_idpaiement`),
  INDEX `fk_Events_Tickets_idx` (`Tickets_idTickets` ASC) VISIBLE,
  INDEX `fk_Events_Hôte1_idx` (`Hôte_idHôte` ASC) VISIBLE,
  INDEX `fk_Events_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_Events_paiement1_idx` (`paiement_idpaiement` ASC) VISIBLE,
  INDEX `fk_Events_Photos1_idx` (`Photos_idPhotos` ASC) VISIBLE,
  INDEX `fk_Events_Date1_idx` (`Date_idDate` ASC) VISIBLE,
  INDEX `fk_Events_qrcode1_idx` (`qrcode_idqrcode` ASC) VISIBLE,
  CONSTRAINT `fk_Events_Tickets`
    FOREIGN KEY (`Tickets_idTickets`)
    REFERENCES `Thetickets`.`Tickets` (`idTickets`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_Hôte1`
    FOREIGN KEY (`Hôte_idHôte`)
    REFERENCES `Thetickets`.`Hôte` (`idHôte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `Thetickets`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_paiement1`
    FOREIGN KEY (`paiement_idpaiement`)
    REFERENCES `Thetickets`.`paiement` (`idpaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_Photos1`
    FOREIGN KEY (`Photos_idPhotos`)
    REFERENCES `Thetickets`.`Photos` (`idPhotos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_Date1`
    FOREIGN KEY (`Date_idDate`)
    REFERENCES `Thetickets`.`Date` (`idDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_qrcode1`
    FOREIGN KEY (`qrcode_idqrcode`)
    REFERENCES `Thetickets`.`qrcode` (`idqrcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Thetickets`.`password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Thetickets`.`password` (
  `idpassword` INT NULL AUTO_INCREMENT,
  `passwordcol` VARCHAR(45) NULL,
  `user_iduser` INT NOT NULL,
  `user_iduser1` INT NOT NULL,
  `user_paiement_idpaiement` INT NOT NULL,
  INDEX `fk_password_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_password_user2_idx` (`user_iduser1` ASC, `user_paiement_idpaiement` ASC) VISIBLE,
  CONSTRAINT `fk_password_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `Thetickets`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_password_user2`
    FOREIGN KEY (`user_iduser1` , `user_paiement_idpaiement`)
    REFERENCES `Thetickets`.`user` (`iduser` , `paiement_idpaiement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
