-- MySQL Script generated by MySQL Workbench
-- Thu Dec 17 15:06:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema c0_thetickets_BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema c0_thetickets_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c0_thetickets_BD` DEFAULT CHARACTER SET utf8 ;
USE `c0_thetickets_BD` ;

-- -----------------------------------------------------
-- Table `c0_thetickets_BD`.`SecteurEntreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c0_thetickets_BD`.`SecteurEntreprise` (
  `idSecteurEntreprise` INT NOT NULL,
  `Nom` VARCHAR(255) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSecteurEntreprise`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c0_thetickets_BD`.`Entreprises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c0_thetickets_BD`.`Entreprises` (
  `idEntreprise` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `Ville` VARCHAR(45) NOT NULL,
  `CodePostal` VARCHAR(45) NOT NULL,
  `Pays` VARCHAR(45) NOT NULL,
  `idSecteurEntreprise` INT NULL,
  PRIMARY KEY (`idEntreprise`),
  INDEX `fk_Entreprises_SecteurEntreprise1_idx` (`idSecteurEntreprise` ASC) VISIBLE,
  CONSTRAINT `fk_Entreprises_SecteurEntreprise1`
    FOREIGN KEY (`idSecteurEntreprise`)
    REFERENCES `c0_thetickets_BD`.`SecteurEntreprise` (`idSecteurEntreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c0_thetickets_BD`.`Utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c0_thetickets_BD`.`Utilisateurs` (
  `idUtilisateur` INT NOT NULL AUTO_INCREMENT,
  `idEntreprise` INT NULL,
  `Nom` VARCHAR(255) NOT NULL,
  `Prenom` VARCHAR(255) NOT NULL,
  `DateDeNaissance` DATE NOT NULL,
  `Genre` TINYINT NULL COMMENT '0 = H\n1= F',
  `AdressEmail` VARCHAR(255) NOT NULL,
  `MotDePasse` VARCHAR(255) NOT NULL,
  `Adresse` VARCHAR(255) NULL,
  `CodePostal` VARCHAR(255) NULL,
  `Ville` VARCHAR(255) NULL,
  `Pays` VARCHAR(255) NULL,
  `Statut` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '0= Utilisateur Normal\n1= SuperAdmin',
  PRIMARY KEY (`idUtilisateur`),
  INDEX `fk_Utilisateurs_Entreprises1_idx` (`idEntreprise` ASC) VISIBLE,
  CONSTRAINT `fk_Utilisateurs_Entreprises1`
    FOREIGN KEY (`idEntreprise`)
    REFERENCES `c0_thetickets_BD`.`Entreprises` (`idEntreprise`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c0_thetickets_BD`.`Evenements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c0_thetickets_BD`.`Evenements` (
  `idEvenement` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(255) NOT NULL,
  `idUtilisateur` INT NOT NULL,
  `Description` TEXT NOT NULL,
  `NbPlaces` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEvenement`),
  INDEX `fk_Evenements_Utilisateurs1_idx` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Evenements_Utilisateurs1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `c0_thetickets_BD`.`Utilisateurs` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c0_thetickets_BD`.`Lieux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c0_thetickets_BD`.`Lieux` (
  `Nom` VARCHAR(255) NOT NULL,
  `idLieu` INT NOT NULL AUTO_INCREMENT,
  `idUtilisateur` INT NULL,
  `Adresse` VARCHAR(255) NOT NULL,
  `CodePostal` VARCHAR(255) NOT NULL,
  `Ville` VARCHAR(255) NOT NULL,
  `Pays` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idLieu`),
  INDEX `fk_Lieux_Utilisateurs1_idx` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Lieux_Utilisateurs1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `c0_thetickets_BD`.`Utilisateurs` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c0_thetickets_BD`.`Dates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c0_thetickets_BD`.`Dates` (
  `idDate` INT NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `idEvenement` INT NOT NULL,
  `idLieu` INT NOT NULL,
  `Prix` DECIMAL(14,2) NOT NULL,
  PRIMARY KEY (`idDate`),
  INDEX `fk_Dates_Evenements_idx` (`idEvenement` ASC) VISIBLE,
  INDEX `fk_Dates_Lieux1_idx` (`idLieu` ASC) VISIBLE,
  CONSTRAINT `fk_Dates_Evenements`
    FOREIGN KEY (`idEvenement`)
    REFERENCES `c0_thetickets_BD`.`Evenements` (`idEvenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dates_Lieux1`
    FOREIGN KEY (`idLieu`)
    REFERENCES `c0_thetickets_BD`.`Lieux` (`idLieu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c0_thetickets_BD`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c0_thetickets_BD`.`Tickets` (
  `idTicket` INT NOT NULL,
  `idDate` INT NOT NULL,
  `idUtilisateur` INT NOT NULL,
  `Prix` DECIMAL(14,2) NOT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `DateNaissance` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTicket`),
  INDEX `fk_Tickets_Dates1_idx` (`idDate` ASC) VISIBLE,
  INDEX `fk_Tickets_Utilisateurs1_idx` (`idUtilisateur` ASC) VISIBLE,
  CONSTRAINT `fk_Tickets_Dates1`
    FOREIGN KEY (`idDate`)
    REFERENCES `c0_thetickets_BD`.`Dates` (`idDate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Utilisateurs1`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `c0_thetickets_BD`.`Utilisateurs` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c0_thetickets_BD`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c0_thetickets_BD`.`Categories` (
  `idCategorie` INT NOT NULL,
  `Nom` VARCHAR(255) NOT NULL,
  `Description` TEXT NOT NULL,
  `Categoriecol` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c0_thetickets_BD`.`Artistes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c0_thetickets_BD`.`Artistes` (
  `idArtiste` INT NOT NULL,
  `NomArtiste` VARCHAR(45) NOT NULL,
  `Nom` VARCHAR(255) NULL,
  `Prenom` VARCHAR(45) NULL,
  `DateNaissance` DATE NULL,
  PRIMARY KEY (`idArtiste`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c0_thetickets_BD`.`Evenements_A_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c0_thetickets_BD`.`Evenements_A_Categories` (
  `idEvenement` INT NOT NULL,
  `idCategorie` INT NOT NULL,
  PRIMARY KEY (`idEvenement`, `idCategorie`),
  INDEX `fk_Evenements_has_Categorie_Categorie1_idx` (`idCategorie` ASC) VISIBLE,
  INDEX `fk_Evenements_has_Categorie_Evenements1_idx` (`idEvenement` ASC) VISIBLE,
  CONSTRAINT `fk_Evenements_has_Categorie_Evenements1`
    FOREIGN KEY (`idEvenement`)
    REFERENCES `c0_thetickets_BD`.`Evenements` (`idEvenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evenements_has_Categorie_Categorie1`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `c0_thetickets_BD`.`Categories` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `c0_thetickets_BD`.`Evenements_A_Artistes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c0_thetickets_BD`.`Evenements_A_Artistes` (
  `idEvenement` INT NOT NULL,
  `idArtiste` INT NOT NULL,
  PRIMARY KEY (`idEvenement`, `idArtiste`),
  INDEX `fk_Evenements_has_Artistes_Artistes1_idx` (`idArtiste` ASC) VISIBLE,
  INDEX `fk_Evenements_has_Artistes_Evenements1_idx` (`idEvenement` ASC) VISIBLE,
  CONSTRAINT `fk_Evenements_has_Artistes_Evenements1`
    FOREIGN KEY (`idEvenement`)
    REFERENCES `c0_thetickets_BD`.`Evenements` (`idEvenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evenements_has_Artistes_Artistes1`
    FOREIGN KEY (`idArtiste`)
    REFERENCES `c0_thetickets_BD`.`Artistes` (`idArtiste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
